### ISSUE TITLE
相同的问题在你这问一下

### ISSUE THREAD

**Issue by ttsite** [cyndicatelabs/GodPotato_CLR#1]
请问这个godpotato原版的不能用Eazfuscator.NET进行混淆操作是什么原因。您这款也是。只要混淆之后执行就出错。但不混淆貌似一些应用产景运行不了。。

**Comment by bopin2020** [comment]
根据你的描述，很容易推理出Eazfuscator混淆器的问题，兼容性没做好。.NET 互操作这块动了很容易出问题，具体情况还得看执行CLR抛的啥异常。

**Comment by ttsite** [comment]
> 根据你的描述，很容易推理出Eazfuscator混淆器的问题，兼容性没做好。.NET 互操作这块动了很容易出问题，具体情况还得看执行CLR抛的啥异常。

![111](https://github.com/cyndicatelabs/GodPotato_CLR/assets/43260559/8020f689-0417-40cc-b1e1-a3b2f90c01c0)

**Comment by bopin2020** [comment]
1. PEVerify 验证下混淆后的godpotato 元数据是否有被损坏
2. 建议拖到Dnspy里面调试吧   这样截图信息有限。
   或者你可以把混淆后的文件传上来，有时间帮你看看。

**Comment by ttsite** [comment]
> 1. PEVerify 验证下混淆后的godpotato 元数据是否有被损坏
> 2. 建议拖到Dnspy里面调试吧   这样截图信息有限。
>    或者你可以把混淆后的文件传上来，有时间帮你看看。

谢谢您的回复。原作者已将这个问题修复了。
